// Autogenerated project case studies data from Google Sheets source
export const caseStudiesData = [
  {
    "id": "riva-beach-resort",
    "title": "RIVA BEACH RESORT",
    "client": "RIVA BEACH RESORT",
    "propertyType": "Resort",
    "location": "Goa",
    "capacity": "100 Rooms",
    "services": [
      "INSTAGRAM HANDLING",
      "META ADS",
      "OTA PROFILE"
    ],
    "tagline": "Deployed optimized direct booking channels for Riva Beach Resort in Goa, India, converting 35% bookings commission-free and securing a high ROAS on digital media campaigns.",
    "imgSrc": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80",
    "imgSrcMobile": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&crop=faces,edges&w=800&h=1600&q=80",
    "kpis": [
      {
        "label": "REVENUE GENERATED",
        "value": "₹45.17 Cr"
      },
      {
        "label": "BOOKINGS GENERATED",
        "value": "28,678"
      }
    ],
    "gaugeScore": 98,
    "gaugeLabel": "Digital Performance Score",
    "scoreBars": [
      {
        "score": 95,
        "max": 100,
        "label": "User Experience (UX)"
      },
      {
        "score": 92,
        "max": 100,
        "label": "Campaign Health Metrics"
      }
    ],
    "statusCards": [
      {
        "label": "Rooms Capacity",
        "value": "100 Rooms"
      },
      {
        "label": "Direct Bookings Rate",
        "value": "35%"
      },
      {
        "label": "Consolidated Ad-Spend",
        "value": "4.80 Cr"
      }
    ],
    "pieData": [
      {
        "name": "Direct Bookings",
        "value": 35,
        "color": "#10b981"
      },
      {
        "name": "OTA Portals",
        "value": 61,
        "color": "#0ea5e9"
      },
      {
        "name": "Offline Groups",
        "value": 4,
        "color": "#f43f5e"
      }
    ],
    "bulletPoints": [
      "Ran high-impact Meta and Google Ads campaigns targeted at premium luxury travellers to scale direct bookings and brand inquiry conversions.",
      "Constructed commission-free direct booking integrations, synchronizing room rates and rate parity controls across booking networks.",
      "Handled premium social content curation and digital marketing, showcasing the property's 100 room inventory, guest suites, and amenities."
    ]
  },
  {
    "id": "anahata-retreat",
    "title": "ANAHATA RETREAT",
    "client": "ANAHATA RETREAT",
    "propertyType": "Resort",
    "location": "Goa",
    "capacity": "20 Rooms",
    "services": [
      "INSTAGRAM HANDLING",
      "META ADS",
      "OTA PROFILE"
    ],
    "tagline": "Deployed optimized direct booking channels for Anahata Retreat in Goa, India, converting 42% bookings commission-free and securing a high ROAS on digital media campaigns.",
    "imgSrc": "https://static.wixstatic.com/media/094a0d_8f8d7eff3154497b853322b4bb2238ff~mv2.jpg/v1/fill/w_1880,h_1020,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/IMG_9289_JPG.jpg",
    "imgSrcMobile": "https://static.wixstatic.com/media/094a0d_8f8d7eff3154497b853322b4bb2238ff~mv2.jpg/v1/fill/w_1000,h_1800,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/IMG_9289_JPG.jpg",
    "kpis": [
      {
        "label": "REVENUE GENERATED",
        "value": "₹9.03 Cr"
      },
      {
        "label": "BOOKINGS GENERATED",
        "value": "5,736"
      }
    ],
    "gaugeScore": 98,
    "gaugeLabel": "Digital Performance Score",
    "scoreBars": [
      {
        "score": 95,
        "max": 100,
        "label": "User Experience (UX)"
      },
      {
        "score": 92,
        "max": 100,
        "label": "Campaign Health Metrics"
      }
    ],
    "statusCards": [
      {
        "label": "Rooms Capacity",
        "value": "20 Rooms"
      },
      {
        "label": "Direct Bookings Rate",
        "value": "42%"
      },
      {
        "label": "Consolidated Ad-Spend",
        "value": "94.00 Lakhs"
      }
    ],
    "pieData": [
      {
        "name": "Direct Bookings",
        "value": 42,
        "color": "#10b981"
      },
      {
        "name": "OTA Portals",
        "value": 53,
        "color": "#0ea5e9"
      },
      {
        "name": "Offline Groups",
        "value": 5,
        "color": "#f43f5e"
      }
    ],
    "bulletPoints": [
      "Ran high-impact Meta and Google Ads campaigns targeted at premium luxury travellers to scale direct bookings and brand inquiry conversions.",
      "Constructed commission-free direct booking integrations, synchronizing room rates and rate parity controls across booking networks.",
      "Handled premium social content curation and digital marketing, showcasing the property's 20 room inventory, guest suites, and amenities."
    ]
  },
  {
    "id": "palma-goa",
    "title": "PALMA GOA",
    "client": "PALMA GOA",
    "propertyType": "Resort",
    "location": "Goa",
    "capacity": "15 Rooms",
    "services": [
      "INSTAGRAM HANDLING",
      "META ADS",
      "OTA PROFILE"
    ],
    "tagline": "Deployed optimized direct booking channels for Palma Goa in Goa, India, converting 45% bookings commission-free and securing a high ROAS on digital media campaigns.",
    "imgSrc": "https://palmagoa.com/wp-content/uploads/2024/09/external_37.webp",
    "imgSrcMobile": "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&h=1600&q=80",
    "kpis": [
      {
        "label": "REVENUE GENERATED",
        "value": "₹6.78 Cr"
      },
      {
        "label": "BOOKINGS GENERATED",
        "value": "4,302"
      }
    ],
    "gaugeScore": 98,
    "gaugeLabel": "Digital Performance Score",
    "scoreBars": [
      {
        "score": 95,
        "max": 100,
        "label": "User Experience (UX)"
      },
      {
        "score": 92,
        "max": 100,
        "label": "Campaign Health Metrics"
      }
    ],
    "statusCards": [
      {
        "label": "Rooms Capacity",
        "value": "15 Rooms"
      },
      {
        "label": "Direct Bookings Rate",
        "value": "45%"
      },
      {
        "label": "Consolidated Ad-Spend",
        "value": "65.00 Lakhs"
      }
    ],
    "pieData": [
      {
        "name": "Direct Bookings",
        "value": 45,
        "color": "#10b981"
      },
      {
        "name": "OTA Portals",
        "value": 49,
        "color": "#0ea5e9"
      },
      {
        "name": "Offline Groups",
        "value": 6,
        "color": "#f43f5e"
      }
    ],
    "bulletPoints": [
      "Ran high-impact Meta and Google Ads campaigns targeted at premium luxury travellers to scale direct bookings and brand inquiry conversions.",
      "Constructed commission-free direct booking integrations, synchronizing room rates and rate parity controls across booking networks.",
      "Handled premium social content curation and digital marketing, showcasing the property's 15 room inventory, guest suites, and amenities."
    ]
  },
  {
    "id": "manuallaya-resort",
    "title": "MANUALLAYA RESORT",
    "client": "MANUALLAYA RESORT",
    "propertyType": "Resort",
    "location": "Manali, HP",
    "capacity": "85 Rooms",
    "services": [
      "INSTAGRAM HANDLING",
      "META ADS",
      "OTA PROFILE"
    ],
    "tagline": "Deployed optimized direct booking channels for Manuallaya Resort in Manali, HP, India, converting 31% bookings commission-free and securing a 5.0x ROAS on digital media campaigns.",
    "imgSrc": "https://homesweb.staah.net/imagelibrary/big_1650533799_3701_A13I6370.jpg",
    "imgSrcMobile": "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=800&h=1600&q=80",
    "kpis": [
      {
        "label": "REVENUE GENERATED",
        "value": "₹38.39 Cr"
      },
      {
        "label": "BOOKINGS GENERATED",
        "value": "24,376"
      }
    ],
    "gaugeScore": 90,
    "gaugeLabel": "Digital Performance Score",
    "scoreBars": [
      {
        "score": 90,
        "max": 100,
        "label": "User Experience (UX)"
      },
      {
        "score": 88,
        "max": 100,
        "label": "Campaign Health Metrics"
      }
    ],
    "statusCards": [
      {
        "label": "Rooms Capacity",
        "value": "85 Rooms"
      },
      {
        "label": "Direct Bookings Rate",
        "value": "31%"
      },
      {
        "label": "Consolidated Ad-Spend",
        "value": "3.25 Cr"
      }
    ],
    "pieData": [
      {
        "name": "Direct Bookings",
        "value": 31,
        "color": "#10b981"
      },
      {
        "name": "OTA Portals",
        "value": 61,
        "color": "#0ea5e9"
      },
      {
        "name": "Offline Groups",
        "value": 8,
        "color": "#f43f5e"
      }
    ],
    "bulletPoints": [
      "Ran high-impact Meta and Google Ads campaigns targeted at premium luxury travellers to scale direct bookings and brand inquiry conversions.",
      "Constructed commission-free direct booking integrations, synchronizing room rates and rate parity controls across booking networks.",
      "Handled premium social content curation and digital marketing, showcasing the property's 85 room inventory, guest suites, and amenities."
    ]
  },
  {
    "id": "the-orchard-greens",
    "title": "THE ORCHARD GREENS",
    "client": "THE ORCHARD GREENS",
    "propertyType": "Resort",
    "location": "Manali, HP",
    "capacity": "54 Rooms",
    "services": [
      "INSTAGRAM HANDLING",
      "META ADS",
      "OTA PROFILE"
    ],
    "tagline": "Deployed optimized direct booking channels for The Orchard Greens in Manali, HP, India, converting 36% bookings commission-free and securing a 5.5x ROAS on digital media campaigns.",
    "imgSrc": "https://www.theorchardgreens.com/resource/images/upload/meat-baked-with-carrots-in-the-oven-PB3WM5Z-1024x683.jpg",
    "imgSrcMobile": "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&h=1600&q=80",
    "kpis": [
      {
        "label": "REVENUE GENERATED",
        "value": "₹24.39 Cr"
      },
      {
        "label": "BOOKINGS GENERATED",
        "value": "15,486"
      }
    ],
    "gaugeScore": 91,
    "gaugeLabel": "Digital Performance Score",
    "scoreBars": [
      {
        "score": 91,
        "max": 100,
        "label": "User Experience (UX)"
      },
      {
        "score": 89,
        "max": 100,
        "label": "Campaign Health Metrics"
      }
    ],
    "statusCards": [
      {
        "label": "Rooms Capacity",
        "value": "54 Rooms"
      },
      {
        "label": "Direct Bookings Rate",
        "value": "36%"
      },
      {
        "label": "Consolidated Ad-Spend",
        "value": "1.73 Cr"
      }
    ],
    "pieData": [
      {
        "name": "Direct Bookings",
        "value": 36,
        "color": "#10b981"
      },
      {
        "name": "OTA Portals",
        "value": 55,
        "color": "#0ea5e9"
      },
      {
        "name": "Offline Groups",
        "value": 9,
        "color": "#f43f5e"
      }
    ],
    "bulletPoints": [
      "Ran high-impact Meta and Google Ads campaigns targeted at premium luxury travellers to scale direct bookings and brand inquiry conversions.",
      "Constructed commission-free direct booking integrations, synchronizing room rates and rate parity controls across booking networks.",
      "Handled premium social content curation and digital marketing, showcasing the property's 54 room inventory, guest suites, and amenities."
    ]
  },
  {
    "id": "woodrock-hotel",
    "title": "WOODROCK HOTEL",
    "client": "WOODROCK HOTEL",
    "propertyType": "Resort",
    "location": "Manali, HP",
    "capacity": "41 Rooms",
    "services": [
      "INSTAGRAM HANDLING",
      "META ADS",
      "OTA PROFILE"
    ],
    "tagline": "Deployed optimized direct booking channels for Woodrock Hotel in Manali, HP, India, converting 40% bookings commission-free and securing a 5.0x ROAS on digital media campaigns.",
    "imgSrc": "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1200&q=80",
    "imgSrcMobile": "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&crop=faces,edges&w=800&h=1600&q=80",
    "kpis": [
      {
        "label": "REVENUE GENERATED",
        "value": "₹18.52 Cr"
      },
      {
        "label": "BOOKINGS GENERATED",
        "value": "11,758"
      }
    ],
    "gaugeScore": 92,
    "gaugeLabel": "Digital Performance Score",
    "scoreBars": [
      {
        "score": 92,
        "max": 100,
        "label": "User Experience (UX)"
      },
      {
        "score": 90,
        "max": 100,
        "label": "Campaign Health Metrics"
      }
    ],
    "statusCards": [
      {
        "label": "Rooms Capacity",
        "value": "41 Rooms"
      },
      {
        "label": "Direct Bookings Rate",
        "value": "40%"
      },
      {
        "label": "Consolidated Ad-Spend",
        "value": "1.20 Cr"
      }
    ],
    "pieData": [
      {
        "name": "Direct Bookings",
        "value": 40,
        "color": "#10b981"
      },
      {
        "name": "OTA Portals",
        "value": 50,
        "color": "#0ea5e9"
      },
      {
        "name": "Offline Groups",
        "value": 10,
        "color": "#f43f5e"
      }
    ],
    "bulletPoints": [
      "Ran high-impact Meta and Google Ads campaigns targeted at premium luxury travellers to scale direct bookings and brand inquiry conversions.",
      "Constructed commission-free direct booking integrations, synchronizing room rates and rate parity controls across booking networks.",
      "Handled premium social content curation and digital marketing, showcasing the property's 41 room inventory, guest suites, and amenities."
    ]
  },
  {
    "id": "snow-valley-resorts",
    "title": "SNOW VALLEY RESORTS",
    "client": "SNOW VALLEY RESORTS",
    "propertyType": "Resort",
    "location": "Manali, HP",
    "capacity": "72 Rooms",
    "services": [
      "INSTAGRAM HANDLING",
      "META ADS",
      "OTA PROFILE"
    ],
    "tagline": "Deployed optimized direct booking channels for Snow Valley Resorts in Manali, HP, India, converting 28% bookings commission-free and securing a 5.5x ROAS on digital media campaigns.",
    "imgSrc": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80",
    "imgSrcMobile": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&crop=faces,edges&w=800&h=1600&q=80",
    "kpis": [
      {
        "label": "REVENUE GENERATED",
        "value": "₹32.52 Cr"
      },
      {
        "label": "BOOKINGS GENERATED",
        "value": "20,648"
      }
    ],
    "gaugeScore": 93,
    "gaugeLabel": "Digital Performance Score",
    "scoreBars": [
      {
        "score": 93,
        "max": 100,
        "label": "User Experience (UX)"
      },
      {
        "score": 91,
        "max": 100,
        "label": "Campaign Health Metrics"
      }
    ],
    "statusCards": [
      {
        "label": "Rooms Capacity",
        "value": "72 Rooms"
      },
      {
        "label": "Direct Bookings Rate",
        "value": "28%"
      },
      {
        "label": "Consolidated Ad-Spend",
        "value": "2.55 Cr"
      }
    ],
    "pieData": [
      {
        "name": "Direct Bookings",
        "value": 28,
        "color": "#10b981"
      },
      {
        "name": "OTA Portals",
        "value": 61,
        "color": "#0ea5e9"
      },
      {
        "name": "Offline Groups",
        "value": 11,
        "color": "#f43f5e"
      }
    ],
    "bulletPoints": [
      "Ran high-impact Meta and Google Ads campaigns targeted at premium luxury travellers to scale direct bookings and brand inquiry conversions.",
      "Constructed commission-free direct booking integrations, synchronizing room rates and rate parity controls across booking networks.",
      "Handled premium social content curation and digital marketing, showcasing the property's 72 room inventory, guest suites, and amenities."
    ]
  },
  {
    "id": "the-whispering-inn",
    "title": "THE WHISPERING INN",
    "client": "THE WHISPERING INN",
    "propertyType": "Resort",
    "location": "Manali, HP",
    "capacity": "24 Rooms",
    "services": [
      "INSTAGRAM HANDLING",
      "META ADS",
      "OTA PROFILE"
    ],
    "tagline": "Deployed optimized direct booking channels for The Whispering Inn in Manali, HP, India, converting 46% bookings commission-free and securing a 4.5x ROAS on digital media campaigns.",
    "imgSrc": "https://images.unsplash.com/photo-1486496146582-9ffcd0b2b2b7?auto=format&fit=crop&w=1200&q=80",
    "imgSrcMobile": "https://images.unsplash.com/photo-1486496146582-9ffcd0b2b2b7?auto=format&fit=crop&crop=faces,edges&w=800&h=1600&q=80",
    "kpis": [
      {
        "label": "REVENUE GENERATED",
        "value": "₹10.84 Cr"
      },
      {
        "label": "BOOKINGS GENERATED",
        "value": "6,883"
      }
    ],
    "gaugeScore": 94,
    "gaugeLabel": "Digital Performance Score",
    "scoreBars": [
      {
        "score": 94,
        "max": 100,
        "label": "User Experience (UX)"
      },
      {
        "score": 92,
        "max": 100,
        "label": "Campaign Health Metrics"
      }
    ],
    "statusCards": [
      {
        "label": "Rooms Capacity",
        "value": "24 Rooms"
      },
      {
        "label": "Direct Bookings Rate",
        "value": "46%"
      },
      {
        "label": "Consolidated Ad-Spend",
        "value": "65.00 Lakhs"
      }
    ],
    "pieData": [
      {
        "name": "Direct Bookings",
        "value": 46,
        "color": "#10b981"
      },
      {
        "name": "OTA Portals",
        "value": 47,
        "color": "#0ea5e9"
      },
      {
        "name": "Offline Groups",
        "value": 7,
        "color": "#f43f5e"
      }
    ],
    "bulletPoints": [
      "Ran high-impact Meta and Google Ads campaigns targeted at premium luxury travellers to scale direct bookings and brand inquiry conversions.",
      "Constructed commission-free direct booking integrations, synchronizing room rates and rate parity controls across booking networks.",
      "Handled premium social content curation and digital marketing, showcasing the property's 24 room inventory, guest suites, and amenities."
    ]
  },
  {
    "id": "kolahoi-green-resort",
    "title": "KOLAHOI GREEN RESORT",
    "client": "KOLAHOI GREEN RESORT",
    "propertyType": "Resort",
    "location": "Kashmir",
    "capacity": "35 Rooms",
    "services": [
      "INSTAGRAM HANDLING",
      "META ADS",
      "OTA PROFILE"
    ],
    "tagline": "Deployed optimized direct booking channels for Kolahoi Green Resort in Kashmir, India, converting 33% bookings commission-free and securing a 6.0x ROAS on digital media campaigns.",
    "imgSrc": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
    "imgSrcMobile": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&crop=faces,edges&w=800&h=1600&q=80",
    "kpis": [
      {
        "label": "REVENUE GENERATED",
        "value": "₹15.81 Cr"
      },
      {
        "label": "BOOKINGS GENERATED",
        "value": "10,037"
      }
    ],
    "gaugeScore": 95,
    "gaugeLabel": "Digital Performance Score",
    "scoreBars": [
      {
        "score": 95,
        "max": 100,
        "label": "User Experience (UX)"
      },
      {
        "score": 93,
        "max": 100,
        "label": "Campaign Health Metrics"
      }
    ],
    "statusCards": [
      {
        "label": "Rooms Capacity",
        "value": "35 Rooms"
      },
      {
        "label": "Direct Bookings Rate",
        "value": "33%"
      },
      {
        "label": "Consolidated Ad-Spend",
        "value": "1.87 Cr"
      }
    ],
    "pieData": [
      {
        "name": "Direct Bookings",
        "value": 33,
        "color": "#10b981"
      },
      {
        "name": "OTA Portals",
        "value": 63,
        "color": "#0ea5e9"
      },
      {
        "name": "Offline Groups",
        "value": 4,
        "color": "#f43f5e"
      }
    ],
    "bulletPoints": [
      "Ran high-impact Meta and Google Ads campaigns targeted at premium luxury travellers to scale direct bookings and brand inquiry conversions.",
      "Constructed commission-free direct booking integrations, synchronizing room rates and rate parity controls across booking networks.",
      "Handled premium social content curation and digital marketing, showcasing the property's 35 room inventory, guest suites, and amenities."
    ]
  },
  {
    "id": "eden-resorts-spa",
    "title": "EDEN RESORTS & SPA",
    "client": "EDEN RESORTS & SPA",
    "propertyType": "Resort",
    "location": "Kashmir",
    "capacity": "45 Rooms",
    "services": [
      "INSTAGRAM HANDLING",
      "META ADS",
      "OTA PROFILE"
    ],
    "tagline": "Deployed optimized direct booking channels for Eden Resorts & Spa in Kashmir, India, converting 38% bookings commission-free and securing a 5.5x ROAS on digital media campaigns.",
    "imgSrc": "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1200&q=80",
    "imgSrcMobile": "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&crop=faces,edges&w=800&h=1600&q=80",
    "kpis": [
      {
        "label": "REVENUE GENERATED",
        "value": "₹20.33 Cr"
      },
      {
        "label": "BOOKINGS GENERATED",
        "value": "12,905"
      }
    ],
    "gaugeScore": 96,
    "gaugeLabel": "Digital Performance Score",
    "scoreBars": [
      {
        "score": 96,
        "max": 100,
        "label": "User Experience (UX)"
      },
      {
        "score": 94,
        "max": 100,
        "label": "Campaign Health Metrics"
      }
    ],
    "statusCards": [
      {
        "label": "Rooms Capacity",
        "value": "45 Rooms"
      },
      {
        "label": "Direct Bookings Rate",
        "value": "38%"
      },
      {
        "label": "Consolidated Ad-Spend",
        "value": "2.14 Cr"
      }
    ],
    "pieData": [
      {
        "name": "Direct Bookings",
        "value": 38,
        "color": "#10b981"
      },
      {
        "name": "OTA Portals",
        "value": 57,
        "color": "#0ea5e9"
      },
      {
        "name": "Offline Groups",
        "value": 5,
        "color": "#f43f5e"
      }
    ],
    "bulletPoints": [
      "Ran high-impact Meta and Google Ads campaigns targeted at premium luxury travellers to scale direct bookings and brand inquiry conversions.",
      "Constructed commission-free direct booking integrations, synchronizing room rates and rate parity controls across booking networks.",
      "Handled premium social content curation and digital marketing, showcasing the property's 45 room inventory, guest suites, and amenities."
    ]
  },
  {
    "id": "hazaar-dastaan",
    "title": "HAZAAR DASTAAN",
    "client": "HAZAAR DASTAAN",
    "propertyType": "Homestay",
    "location": "Kashmir",
    "capacity": "10 Rooms",
    "services": [
      "INSTAGRAM HANDLING",
      "META ADS",
      "OTA PROFILE"
    ],
    "tagline": "Deployed optimized direct booking channels for Hazaar Dastaan in Kashmir, India, converting 44% bookings commission-free and securing a 6.5x ROAS on digital media campaigns.",
    "imgSrc": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80",
    "imgSrcMobile": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&crop=faces,edges&w=800&h=1600&q=80",
    "kpis": [
      {
        "label": "REVENUE GENERATED",
        "value": "₹3.01 Cr"
      },
      {
        "label": "BOOKINGS GENERATED",
        "value": "2,868"
      }
    ],
    "gaugeScore": 97,
    "gaugeLabel": "Digital Performance Score",
    "scoreBars": [
      {
        "score": 97,
        "max": 100,
        "label": "User Experience (UX)"
      },
      {
        "score": 95,
        "max": 100,
        "label": "Campaign Health Metrics"
      }
    ],
    "statusCards": [
      {
        "label": "Rooms Capacity",
        "value": "10 Rooms"
      },
      {
        "label": "Direct Bookings Rate",
        "value": "44%"
      },
      {
        "label": "Consolidated Ad-Spend",
        "value": "32.00 Lakhs"
      }
    ],
    "pieData": [
      {
        "name": "Direct Bookings",
        "value": 44,
        "color": "#10b981"
      },
      {
        "name": "OTA Portals",
        "value": 50,
        "color": "#0ea5e9"
      },
      {
        "name": "Offline Groups",
        "value": 6,
        "color": "#f43f5e"
      }
    ],
    "bulletPoints": [
      "Ran high-impact Meta and Google Ads campaigns targeted at premium luxury travellers to scale direct bookings and brand inquiry conversions.",
      "Constructed commission-free direct booking integrations, synchronizing room rates and rate parity controls across booking networks.",
      "Handled premium social content curation and digital marketing, showcasing the property's 10 room inventory, guest suites, and amenities."
    ]
  },
  {
    "id": "chembarathi-wayanad",
    "title": "CHEMBARATHI WAYANAD",
    "client": "CHEMBARATHI WAYANAD",
    "propertyType": "Resort",
    "location": "Kerala",
    "capacity": "8 Rooms",
    "services": [
      "INSTAGRAM HANDLING",
      "META ADS",
      "OTA PROFILE"
    ],
    "tagline": "Deployed optimized direct booking channels for Chembarathi Wayanad in Kerala, India, converting 45% bookings commission-free and securing a 5.5x ROAS on digital media campaigns.",
    "imgSrc": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=1200&q=80",
    "imgSrcMobile": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&crop=faces,edges&w=800&h=1600&q=80",
    "kpis": [
      {
        "label": "REVENUE GENERATED",
        "value": "₹3.61 Cr"
      },
      {
        "label": "BOOKINGS GENERATED",
        "value": "2,294"
      }
    ],
    "gaugeScore": 98,
    "gaugeLabel": "Digital Performance Score",
    "scoreBars": [
      {
        "score": 90,
        "max": 100,
        "label": "User Experience (UX)"
      },
      {
        "score": 96,
        "max": 100,
        "label": "Campaign Health Metrics"
      }
    ],
    "statusCards": [
      {
        "label": "Rooms Capacity",
        "value": "8 Rooms"
      },
      {
        "label": "Direct Bookings Rate",
        "value": "45%"
      },
      {
        "label": "Consolidated Ad-Spend",
        "value": "32.00 Lakhs"
      }
    ],
    "pieData": [
      {
        "name": "Direct Bookings",
        "value": 45,
        "color": "#10b981"
      },
      {
        "name": "OTA Portals",
        "value": 46,
        "color": "#0ea5e9"
      },
      {
        "name": "Offline Groups",
        "value": 9,
        "color": "#f43f5e"
      }
    ],
    "bulletPoints": [
      "Ran high-impact Meta and Google Ads campaigns targeted at premium luxury travellers to scale direct bookings and brand inquiry conversions.",
      "Constructed commission-free direct booking integrations, synchronizing room rates and rate parity controls across booking networks.",
      "Handled premium social content curation and digital marketing, showcasing the property's 8 room inventory, guest suites, and amenities."
    ]
  },
  {
    "id": "mount-xanadu",
    "title": "MOUNT XANADU",
    "client": "MOUNT XANADU",
    "propertyType": "Resort",
    "location": "Kerala",
    "capacity": "25 Rooms",
    "services": [
      "INSTAGRAM HANDLING",
      "META ADS",
      "OTA PROFILE"
    ],
    "tagline": "Deployed optimized direct booking channels for Mount Xanadu in Kerala, India, converting 30% bookings commission-free and securing a 6.0x ROAS on digital media campaigns.",
    "imgSrc": "https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=1200&q=80",
    "imgSrcMobile": "https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&crop=faces,edges&w=800&h=1600&q=80",
    "kpis": [
      {
        "label": "REVENUE GENERATED",
        "value": "₹11.29 Cr"
      },
      {
        "label": "BOOKINGS GENERATED",
        "value": "7,169"
      }
    ],
    "gaugeScore": 90,
    "gaugeLabel": "Digital Performance Score",
    "scoreBars": [
      {
        "score": 91,
        "max": 100,
        "label": "User Experience (UX)"
      },
      {
        "score": 97,
        "max": 100,
        "label": "Campaign Health Metrics"
      }
    ],
    "statusCards": [
      {
        "label": "Rooms Capacity",
        "value": "25 Rooms"
      },
      {
        "label": "Direct Bookings Rate",
        "value": "30%"
      },
      {
        "label": "Consolidated Ad-Spend",
        "value": "1.45 Cr"
      }
    ],
    "pieData": [
      {
        "name": "Direct Bookings",
        "value": 30,
        "color": "#10b981"
      },
      {
        "name": "OTA Portals",
        "value": 62,
        "color": "#0ea5e9"
      },
      {
        "name": "Offline Groups",
        "value": 8,
        "color": "#f43f5e"
      }
    ],
    "bulletPoints": [
      "Ran high-impact Meta and Google Ads campaigns targeted at premium luxury travellers to scale direct bookings and brand inquiry conversions.",
      "Constructed commission-free direct booking integrations, synchronizing room rates and rate parity controls across booking networks.",
      "Handled premium social content curation and digital marketing, showcasing the property's 25 room inventory, guest suites, and amenities."
    ]
  },
  {
    "id": "willow-resorts",
    "title": "WILLOW RESORTS",
    "client": "WILLOW RESORTS",
    "propertyType": "Resort",
    "location": "Kerala",
    "capacity": "12 Rooms",
    "services": [
      "INSTAGRAM HANDLING",
      "GOOGLE ADS",
      "META ADS",
      "OTA PROFILE"
    ],
    "tagline": "Deployed optimized direct booking channels for Willow Resorts in Kerala, India, converting 34% bookings commission-free and securing a 5.0x ROAS on digital media campaigns.",
    "imgSrc": "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1200&q=80",
    "imgSrcMobile": "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&crop=faces,edges&w=800&h=1600&q=80",
    "kpis": [
      {
        "label": "REVENUE GENERATED",
        "value": "₹5.42 Cr"
      },
      {
        "label": "BOOKINGS GENERATED",
        "value": "3,441"
      }
    ],
    "gaugeScore": 91,
    "gaugeLabel": "Digital Performance Score",
    "scoreBars": [
      {
        "score": 92,
        "max": 100,
        "label": "User Experience (UX)"
      },
      {
        "score": 98,
        "max": 100,
        "label": "Campaign Health Metrics"
      }
    ],
    "statusCards": [
      {
        "label": "Rooms Capacity",
        "value": "12 Rooms"
      },
      {
        "label": "Direct Bookings Rate",
        "value": "34%"
      },
      {
        "label": "Consolidated Ad-Spend",
        "value": "39.00 Lakhs"
      }
    ],
    "pieData": [
      {
        "name": "Direct Bookings",
        "value": 34,
        "color": "#10b981"
      },
      {
        "name": "OTA Portals",
        "value": 57,
        "color": "#0ea5e9"
      },
      {
        "name": "Offline Groups",
        "value": 9,
        "color": "#f43f5e"
      }
    ],
    "bulletPoints": [
      "Ran high-impact Meta and Google Ads campaigns targeted at premium luxury travellers to scale direct bookings and brand inquiry conversions.",
      "Constructed commission-free direct booking integrations, synchronizing room rates and rate parity controls across booking networks.",
      "Handled premium social content curation and digital marketing, showcasing the property's 12 room inventory, guest suites, and amenities."
    ]
  },
  {
    "id": "wayanad-silverwoods",
    "title": "WAYANAD SILVERWOODS",
    "client": "WAYANAD SILVERWOODS",
    "propertyType": "Resort",
    "location": "Wayanad, Kerala",
    "capacity": "40 Rooms",
    "services": [
      "INSTAGRAM HANDLING",
      "GOOGLE ADS",
      "META ADS",
      "OTA PROFILE"
    ],
    "tagline": "Deployed optimized direct booking channels for Wayanad Silverwoods in Wayanad, Kerala, India, converting 41% bookings commission-free and securing a 5.5x ROAS on digital media campaigns.",
    "imgSrc": "https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=1200&q=80",
    "imgSrcMobile": "https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&crop=faces,edges&w=800&h=1600&q=80",
    "kpis": [
      {
        "label": "REVENUE GENERATED",
        "value": "₹18.07 Cr"
      },
      {
        "label": "BOOKINGS GENERATED",
        "value": "11,471"
      }
    ],
    "gaugeScore": 92,
    "gaugeLabel": "Digital Performance Score",
    "scoreBars": [
      {
        "score": 93,
        "max": 100,
        "label": "User Experience (UX)"
      },
      {
        "score": 88,
        "max": 100,
        "label": "Campaign Health Metrics"
      }
    ],
    "statusCards": [
      {
        "label": "Rooms Capacity",
        "value": "40 Rooms"
      },
      {
        "label": "Direct Bookings Rate",
        "value": "41%"
      },
      {
        "label": "Consolidated Ad-Spend",
        "value": "2.29 Cr"
      }
    ],
    "pieData": [
      {
        "name": "Direct Bookings",
        "value": 41,
        "color": "#10b981"
      },
      {
        "name": "OTA Portals",
        "value": 49,
        "color": "#0ea5e9"
      },
      {
        "name": "Offline Groups",
        "value": 10,
        "color": "#f43f5e"
      }
    ],
    "bulletPoints": [
      "Ran high-impact Meta and Google Ads campaigns targeted at premium luxury travellers to scale direct bookings and brand inquiry conversions.",
      "Constructed commission-free direct booking integrations, synchronizing room rates and rate parity controls across booking networks.",
      "Handled premium social content curation and digital marketing, showcasing the property's 40 room inventory, guest suites, and amenities."
    ]
  },
  {
    "id": "pepper-trail",
    "title": "PEPPER TRAIL",
    "client": "PEPPER TRAIL",
    "propertyType": "Resort",
    "location": "Wayanad, Kerala",
    "capacity": "10 Rooms",
    "services": [
      "INSTAGRAM HANDLING",
      "GOOGLE ADS",
      "META ADS",
      "OTA PROFILE"
    ],
    "tagline": "Deployed optimized direct booking channels for Pepper Trail in Wayanad, Kerala, India, converting 46% bookings commission-free and securing a 6.5x ROAS on digital media campaigns.",
    "imgSrc": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=1200&q=80",
    "imgSrcMobile": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&crop=faces,edges&w=800&h=1600&q=80",
    "kpis": [
      {
        "label": "REVENUE GENERATED",
        "value": "₹4.52 Cr"
      },
      {
        "label": "BOOKINGS GENERATED",
        "value": "2,868"
      }
    ],
    "gaugeScore": 93,
    "gaugeLabel": "Digital Performance Score",
    "scoreBars": [
      {
        "score": 94,
        "max": 100,
        "label": "User Experience (UX)"
      },
      {
        "score": 89,
        "max": 100,
        "label": "Campaign Health Metrics"
      }
    ],
    "statusCards": [
      {
        "label": "Rooms Capacity",
        "value": "10 Rooms"
      },
      {
        "label": "Direct Bookings Rate",
        "value": "46%"
      },
      {
        "label": "Consolidated Ad-Spend",
        "value": "85.00 Lakhs"
      }
    ],
    "pieData": [
      {
        "name": "Direct Bookings",
        "value": 46,
        "color": "#10b981"
      },
      {
        "name": "OTA Portals",
        "value": 49,
        "color": "#0ea5e9"
      },
      {
        "name": "Offline Groups",
        "value": 5,
        "color": "#f43f5e"
      }
    ],
    "bulletPoints": [
      "Ran high-impact Meta and Google Ads campaigns targeted at premium luxury travellers to scale direct bookings and brand inquiry conversions.",
      "Constructed commission-free direct booking integrations, synchronizing room rates and rate parity controls across booking networks.",
      "Handled premium social content curation and digital marketing, showcasing the property's 10 room inventory, guest suites, and amenities."
    ]
  },
  {
    "id": "siri-nature-roost",
    "title": "SIRI NATURE ROOST",
    "client": "SIRI NATURE ROOST",
    "propertyType": "Resort",
    "location": "Chikmagalur",
    "capacity": "42 Rooms",
    "services": [
      "INSTAGRAM HANDLING",
      "GOOGLE ADS",
      "META ADS",
      "TECH SUPPORT",
      "OTA PROFILE"
    ],
    "tagline": "Deployed optimized direct booking channels for Siri Nature Roost in Chikmagalur, India, converting 39% bookings commission-free and securing a 6.0x ROAS on digital media campaigns.",
    "imgSrc": "https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=1200&q=80",
    "imgSrcMobile": "https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&crop=faces,edges&w=800&h=1600&q=80",
    "kpis": [
      {
        "label": "REVENUE GENERATED",
        "value": "₹18.97 Cr"
      },
      {
        "label": "BOOKINGS GENERATED",
        "value": "12,045"
      }
    ],
    "gaugeScore": 96,
    "gaugeLabel": "Digital Performance Score",
    "scoreBars": [
      {
        "score": 97,
        "max": 100,
        "label": "User Experience (UX)"
      },
      {
        "score": 92,
        "max": 100,
        "label": "Campaign Health Metrics"
      }
    ],
    "statusCards": [
      {
        "label": "Rooms Capacity",
        "value": "42 Rooms"
      },
      {
        "label": "Direct Bookings Rate",
        "value": "39%"
      },
      {
        "label": "Consolidated Ad-Spend",
        "value": "3.75 Cr"
      }
    ],
    "pieData": [
      {
        "name": "Direct Bookings",
        "value": 39,
        "color": "#10b981"
      },
      {
        "name": "OTA Portals",
        "value": 56,
        "color": "#0ea5e9"
      },
      {
        "name": "Offline Groups",
        "value": 5,
        "color": "#f43f5e"
      }
    ],
    "bulletPoints": [
      "Ran high-impact Meta and Google Ads campaigns targeted at premium luxury travellers to scale direct bookings and brand inquiry conversions.",
      "Constructed commission-free direct booking integrations, synchronizing room rates and rate parity controls across booking networks.",
      "Handled premium social content curation and digital marketing, showcasing the property's 42 room inventory, guest suites, and amenities."
    ]
  },
  {
    "id": "vismita-county",
    "title": "VISMITA COUNTY",
    "client": "VISMITA COUNTY",
    "propertyType": "Resort",
    "location": "Chikmagalur",
    "capacity": "25 Rooms",
    "services": [
      "INSTAGRAM HANDLING",
      "GOOGLE ADS",
      "META ADS",
      "OTA PROFILE"
    ],
    "tagline": "Deployed optimized direct booking channels for Vismita County in Chikmagalur, India, converting 43% bookings commission-free and securing a 5.5x ROAS on digital media campaigns.",
    "imgSrc": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=2000&q=85",
    "imgSrcMobile": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&crop=faces,edges&w=800&h=1600&q=85",
    "kpis": [
      {
        "label": "REVENUE GENERATED",
        "value": "₹11.29 Cr"
      },
      {
        "label": "BOOKINGS GENERATED",
        "value": "7,169"
      }
    ],
    "gaugeScore": 97,
    "gaugeLabel": "Digital Performance Score",
    "scoreBars": [
      {
        "score": 90,
        "max": 100,
        "label": "User Experience (UX)"
      },
      {
        "score": 93,
        "max": 100,
        "label": "Campaign Health Metrics"
      }
    ],
    "statusCards": [
      {
        "label": "Rooms Capacity",
        "value": "25 Rooms"
      },
      {
        "label": "Direct Bookings Rate",
        "value": "43%"
      },
      {
        "label": "Consolidated Ad-Spend",
        "value": "1.62 Cr"
      }
    ],
    "pieData": [
      {
        "name": "Direct Bookings",
        "value": 43,
        "color": "#10b981"
      },
      {
        "name": "OTA Portals",
        "value": 51,
        "color": "#0ea5e9"
      },
      {
        "name": "Offline Groups",
        "value": 6,
        "color": "#f43f5e"
      }
    ],
    "bulletPoints": [
      "Ran high-impact Meta and Google Ads campaigns targeted at premium luxury travellers to scale direct bookings and brand inquiry conversions.",
      "Constructed commission-free direct booking integrations, synchronizing room rates and rate parity controls across booking networks.",
      "Handled premium social content curation and digital marketing, showcasing the property's 25 room inventory, guest suites, and amenities."
    ]
  },
  {
    "id": "mookanana-resort",
    "title": "MOOKANANA RESORT",
    "client": "MOOKANANA RESORT",
    "propertyType": "Resort",
    "location": "Sakleshpur",
    "capacity": "22 Rooms",
    "services": [
      "INSTAGRAM HANDLING",
      "GOOGLE ADS",
      "META ADS",
      "OTA PROFILE"
    ],
    "tagline": "Deployed optimized direct booking channels for Mookanana Resort in Sakleshpur, India, converting 42% bookings commission-free and securing a 5.5x ROAS on digital media campaigns.",
    "imgSrc": "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=2000&q=85",
    "imgSrcMobile": "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&crop=faces,edges&w=800&h=1600&q=85",
    "kpis": [
      {
        "label": "REVENUE GENERATED",
        "value": "₹9.94 Cr"
      },
      {
        "label": "BOOKINGS GENERATED",
        "value": "6,309"
      }
    ],
    "gaugeScore": 90,
    "gaugeLabel": "Digital Performance Score",
    "scoreBars": [
      {
        "score": 92,
        "max": 100,
        "label": "User Experience (UX)"
      },
      {
        "score": 95,
        "max": 100,
        "label": "Campaign Health Metrics"
      }
    ],
    "statusCards": [
      {
        "label": "Rooms Capacity",
        "value": "22 Rooms"
      },
      {
        "label": "Direct Bookings Rate",
        "value": "42%"
      },
      {
        "label": "Consolidated Ad-Spend",
        "value": "1.08 Cr"
      }
    ],
    "pieData": [
      {
        "name": "Direct Bookings",
        "value": 42,
        "color": "#10b981"
      },
      {
        "name": "OTA Portals",
        "value": 50,
        "color": "#0ea5e9"
      },
      {
        "name": "Offline Groups",
        "value": 8,
        "color": "#f43f5e"
      }
    ],
    "bulletPoints": [
      "Ran high-impact Meta and Google Ads campaigns targeted at premium luxury travellers to scale direct bookings and brand inquiry conversions.",
      "Constructed commission-free direct booking integrations, synchronizing room rates and rate parity controls across booking networks.",
      "Handled premium social content curation and digital marketing, showcasing the property's 22 room inventory, guest suites, and amenities."
    ]
  },
  {
    "id": "sea-shells-agatti",
    "title": "SEA SHELLS AGATTI",
    "client": "SEA SHELLS AGATTI",
    "propertyType": "Resort",
    "location": "Lakshadweep",
    "capacity": "18 Rooms",
    "services": [
      "INSTAGRAM HANDLING",
      "GOOGLE ADS",
      "META ADS",
      "OTA PROFILE"
    ],
    "tagline": "Deployed optimized direct booking channels for Sea Shells Agatti in Lakshadweep, India, converting 36% bookings commission-free and securing a 6.0x ROAS on digital media campaigns.",
    "imgSrc": "https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=1200&q=80",
    "imgSrcMobile": "https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&crop=faces,edges&w=800&h=1600&q=80",
    "kpis": [
      {
        "label": "REVENUE GENERATED",
        "value": "₹8.13 Cr"
      },
      {
        "label": "BOOKINGS GENERATED",
        "value": "5,162"
      }
    ],
    "gaugeScore": 92,
    "gaugeLabel": "Digital Performance Score",
    "scoreBars": [
      {
        "score": 94,
        "max": 100,
        "label": "User Experience (UX)"
      },
      {
        "score": 97,
        "max": 100,
        "label": "Campaign Health Metrics"
      }
    ],
    "statusCards": [
      {
        "label": "Rooms Capacity",
        "value": "18 Rooms"
      },
      {
        "label": "Direct Bookings Rate",
        "value": "36%"
      },
      {
        "label": "Consolidated Ad-Spend",
        "value": "1.22 Cr"
      }
    ],
    "pieData": [
      {
        "name": "Direct Bookings",
        "value": 36,
        "color": "#10b981"
      },
      {
        "name": "OTA Portals",
        "value": 54,
        "color": "#0ea5e9"
      },
      {
        "name": "Offline Groups",
        "value": 10,
        "color": "#f43f5e"
      }
    ],
    "bulletPoints": [
      "Ran high-impact Meta and Google Ads campaigns targeted at premium luxury travellers to scale direct bookings and brand inquiry conversions.",
      "Constructed commission-free direct booking integrations, synchronizing room rates and rate parity controls across booking networks.",
      "Handled premium social content curation and digital marketing, showcasing the property's 18 room inventory, guest suites, and amenities."
    ]
  },
  {
    "id": "the-machan",
    "title": "THE MACHAN",
    "client": "THE MACHAN",
    "propertyType": "Resort",
    "location": "Lonavala",
    "capacity": "29 Rooms",
    "services": [
      "INSTAGRAM HANDLING",
      "META ADS",
      "OTA PROFILE"
    ],
    "tagline": "Deployed optimized direct booking channels for The Machan in Lonavala, India, converting 40% bookings commission-free and securing a 6.5x ROAS on digital media campaigns.",
    "imgSrc": "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1200&q=80",
    "imgSrcMobile": "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&crop=faces,edges&w=800&h=1600&q=80",
    "kpis": [
      {
        "label": "REVENUE GENERATED",
        "value": "₹13.10 Cr"
      },
      {
        "label": "BOOKINGS GENERATED",
        "value": "8,317"
      }
    ],
    "gaugeScore": 94,
    "gaugeLabel": "Digital Performance Score",
    "scoreBars": [
      {
        "score": 96,
        "max": 100,
        "label": "User Experience (UX)"
      },
      {
        "score": 88,
        "max": 100,
        "label": "Campaign Health Metrics"
      }
    ],
    "statusCards": [
      {
        "label": "Rooms Capacity",
        "value": "29 Rooms"
      },
      {
        "label": "Direct Bookings Rate",
        "value": "40%"
      },
      {
        "label": "Consolidated Ad-Spend",
        "value": "2.56 Cr"
      }
    ],
    "pieData": [
      {
        "name": "Direct Bookings",
        "value": 40,
        "color": "#10b981"
      },
      {
        "name": "OTA Portals",
        "value": 57,
        "color": "#0ea5e9"
      },
      {
        "name": "Offline Groups",
        "value": 3,
        "color": "#f43f5e"
      }
    ],
    "bulletPoints": [
      "Ran high-impact Meta and Google Ads campaigns targeted at premium luxury travellers to scale direct bookings and brand inquiry conversions.",
      "Constructed commission-free direct booking integrations, synchronizing room rates and rate parity controls across booking networks.",
      "Handled premium social content curation and digital marketing, showcasing the property's 29 room inventory, guest suites, and amenities."
    ]
  },
  {
    "id": "via-lakhela-resort",
    "title": "VIA LAKHELA RESORT",
    "client": "VIA LAKHELA RESORT",
    "propertyType": "Resort",
    "location": "Rajasthan",
    "capacity": "60 Rooms",
    "services": [
      "INSTAGRAM HANDLING",
      "META ADS",
      "OTA PROFILE"
    ],
    "tagline": "Deployed optimized direct booking channels for Via Lakhela Resort in Rajasthan, India, converting 44% bookings commission-free and securing a 5.5x ROAS on digital media campaigns.",
    "imgSrc": "https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?auto=format&fit=crop&w=1200&q=80",
    "imgSrcMobile": "https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?auto=format&fit=crop&crop=faces,edges&w=800&h=1600&q=80",
    "kpis": [
      {
        "label": "REVENUE GENERATED",
        "value": "₹27.10 Cr"
      },
      {
        "label": "BOOKINGS GENERATED",
        "value": "17,207"
      }
    ],
    "gaugeScore": 96,
    "gaugeLabel": "Digital Performance Score",
    "scoreBars": [
      {
        "score": 90,
        "max": 100,
        "label": "User Experience (UX)"
      },
      {
        "score": 90,
        "max": 100,
        "label": "Campaign Health Metrics"
      }
    ],
    "statusCards": [
      {
        "label": "Rooms Capacity",
        "value": "60 Rooms"
      },
      {
        "label": "Direct Bookings Rate",
        "value": "44%"
      },
      {
        "label": "Consolidated Ad-Spend",
        "value": "2.06 Cr"
      }
    ],
    "pieData": [
      {
        "name": "Direct Bookings",
        "value": 44,
        "color": "#10b981"
      },
      {
        "name": "OTA Portals",
        "value": 51,
        "color": "#0ea5e9"
      },
      {
        "name": "Offline Groups",
        "value": 5,
        "color": "#f43f5e"
      }
    ],
    "bulletPoints": [
      "Ran high-impact Meta and Google Ads campaigns targeted at premium luxury travellers to scale direct bookings and brand inquiry conversions.",
      "Constructed commission-free direct booking integrations, synchronizing room rates and rate parity controls across booking networks.",
      "Handled premium social content curation and digital marketing, showcasing the property's 60 room inventory, guest suites, and amenities."
    ]
  },
  {
    "id": "anopura-jaipur",
    "title": "ANOPURA JAIPUR",
    "client": "ANOPURA JAIPUR",
    "propertyType": "Resort",
    "location": "Rajasthan",
    "capacity": "10 Rooms",
    "services": [
      "INSTAGRAM HANDLING",
      "META ADS",
      "OTA PROFILE"
    ],
    "tagline": "Deployed optimized direct booking channels for Anopura Jaipur in Rajasthan, India, converting 45% bookings commission-free and securing a 7.0x ROAS on digital media campaigns.",
    "imgSrc": "https://images.unsplash.com/photo-1598977123418-45f04b615237?auto=format&fit=crop&w=1200&q=80",
    "imgSrcMobile": "https://images.unsplash.com/photo-1598977123418-45f04b615237?auto=format&fit=crop&crop=faces,edges&w=800&h=1600&q=80",
    "kpis": [
      {
        "label": "REVENUE GENERATED",
        "value": "₹4.52 Cr"
      },
      {
        "label": "BOOKINGS GENERATED",
        "value": "2,868"
      }
    ],
    "gaugeScore": 97,
    "gaugeLabel": "Digital Performance Score",
    "scoreBars": [
      {
        "score": 91,
        "max": 100,
        "label": "User Experience (UX)"
      },
      {
        "score": 91,
        "max": 100,
        "label": "Campaign Health Metrics"
      }
    ],
    "statusCards": [
      {
        "label": "Rooms Capacity",
        "value": "10 Rooms"
      },
      {
        "label": "Direct Bookings Rate",
        "value": "45%"
      },
      {
        "label": "Consolidated Ad-Spend",
        "value": "94.00 Lakhs"
      }
    ],
    "pieData": [
      {
        "name": "Direct Bookings",
        "value": 45,
        "color": "#10b981"
      },
      {
        "name": "OTA Portals",
        "value": 50,
        "color": "#0ea5e9"
      },
      {
        "name": "Offline Groups",
        "value": 5,
        "color": "#f43f5e"
      }
    ],
    "bulletPoints": [
      "Ran high-impact Meta and Google Ads campaigns targeted at premium luxury travellers to scale direct bookings and brand inquiry conversions.",
      "Constructed commission-free direct booking integrations, synchronizing room rates and rate parity controls across booking networks.",
      "Handled premium social content curation and digital marketing, showcasing the property's 10 room inventory, guest suites, and amenities."
    ]
  },
  {
    "id": "vasant-kunj-resort",
    "title": "VASANT KUNJ RESORT",
    "client": "VASANT KUNJ RESORT",
    "propertyType": "Resort",
    "location": "Udaipur, RJ",
    "capacity": "30 Rooms",
    "services": [
      "INSTAGRAM HANDLING",
      "GOOGLE ADS",
      "META ADS",
      "OTA PROFILE"
    ],
    "tagline": "Deployed optimized direct booking channels for Vasant Kunj Resort in Udaipur, RJ, India, converting 33% bookings commission-free and securing a 5.5x ROAS on digital media campaigns.",
    "imgSrc": "https://images.unsplash.com/photo-1601999109332-542b18dbec57?auto=format&fit=crop&w=1200&q=80",
    "imgSrcMobile": "https://images.unsplash.com/photo-1601999109332-542b18dbec57?auto=format&fit=crop&crop=faces,edges&w=800&h=1600&q=80",
    "kpis": [
      {
        "label": "REVENUE GENERATED",
        "value": "₹13.55 Cr"
      },
      {
        "label": "BOOKINGS GENERATED",
        "value": "8,603"
      }
    ],
    "gaugeScore": 98,
    "gaugeLabel": "Digital Performance Score",
    "scoreBars": [
      {
        "score": 92,
        "max": 100,
        "label": "User Experience (UX)"
      },
      {
        "score": 92,
        "max": 100,
        "label": "Campaign Health Metrics"
      }
    ],
    "statusCards": [
      {
        "label": "Rooms Capacity",
        "value": "30 Rooms"
      },
      {
        "label": "Direct Bookings Rate",
        "value": "33%"
      },
      {
        "label": "Consolidated Ad-Spend",
        "value": "1.02 Cr"
      }
    ],
    "pieData": [
      {
        "name": "Direct Bookings",
        "value": 33,
        "color": "#10b981"
      },
      {
        "name": "OTA Portals",
        "value": 60,
        "color": "#0ea5e9"
      },
      {
        "name": "Offline Groups",
        "value": 7,
        "color": "#f43f5e"
      }
    ],
    "bulletPoints": [
      "Ran high-impact Meta and Google Ads campaigns targeted at premium luxury travellers to scale direct bookings and brand inquiry conversions.",
      "Constructed commission-free direct booking integrations, synchronizing room rates and rate parity controls across booking networks.",
      "Handled premium social content curation and digital marketing, showcasing the property's 30 room inventory, guest suites, and amenities."
    ]
  },
  {
    "id": "shahpura-hotels",
    "title": "SHAHPURA HOTELS",
    "client": "SHAHPURA HOTELS",
    "propertyType": "Resort",
    "location": "Jaipur, RJ",
    "capacity": "65 Rooms",
    "services": [
      "INSTAGRAM HANDLING",
      "GOOGLE ADS",
      "META ADS",
      "OTA PROFILE"
    ],
    "tagline": "Deployed optimized direct booking channels for Shahpura Hotels in Jaipur, RJ, India, converting 34% bookings commission-free and securing a 6.5x ROAS on digital media campaigns.",
    "imgSrc": "https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?auto=format&fit=crop&w=1200&q=80",
    "imgSrcMobile": "https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?auto=format&fit=crop&crop=faces,edges&w=800&h=1600&q=80",
    "kpis": [
      {
        "label": "REVENUE GENERATED",
        "value": "₹29.36 Cr"
      },
      {
        "label": "BOOKINGS GENERATED",
        "value": "18,641"
      }
    ],
    "gaugeScore": 91,
    "gaugeLabel": "Digital Performance Score",
    "scoreBars": [
      {
        "score": 94,
        "max": 100,
        "label": "User Experience (UX)"
      },
      {
        "score": 94,
        "max": 100,
        "label": "Campaign Health Metrics"
      }
    ],
    "statusCards": [
      {
        "label": "Rooms Capacity",
        "value": "65 Rooms"
      },
      {
        "label": "Direct Bookings Rate",
        "value": "34%"
      },
      {
        "label": "Consolidated Ad-Spend",
        "value": "2.85 Cr"
      }
    ],
    "pieData": [
      {
        "name": "Direct Bookings",
        "value": 34,
        "color": "#10b981"
      },
      {
        "name": "OTA Portals",
        "value": 57,
        "color": "#0ea5e9"
      },
      {
        "name": "Offline Groups",
        "value": 9,
        "color": "#f43f5e"
      }
    ],
    "bulletPoints": [
      "Ran high-impact Meta and Google Ads campaigns targeted at premium luxury travellers to scale direct bookings and brand inquiry conversions.",
      "Constructed commission-free direct booking integrations, synchronizing room rates and rate parity controls across booking networks.",
      "Handled premium social content curation and digital marketing, showcasing the property's 65 room inventory, guest suites, and amenities."
    ]
  },
  {
    "id": "vaikundam-legacy",
    "title": "VAIKUNDAM LEGACY",
    "client": "VAIKUNDAM LEGACY",
    "propertyType": "Homestay",
    "location": "Tamil Nadu",
    "capacity": "6 Rooms",
    "services": [
      "INSTAGRAM HANDLING",
      "GOOGLE ADS",
      "META ADS",
      "OTA PROFILE"
    ],
    "tagline": "Deployed optimized direct booking channels for Vaikundam Legacy in Tamil Nadu, India, converting 43% bookings commission-free and securing a 6.0x ROAS on digital media campaigns.",
    "imgSrc": "https://images.unsplash.com/photo-1598977123418-45f04b615237?auto=format&fit=crop&w=1200&q=80",
    "imgSrcMobile": "https://images.unsplash.com/photo-1598977123418-45f04b615237?auto=format&fit=crop&crop=faces,edges&w=800&h=1600&q=80",
    "kpis": [
      {
        "label": "REVENUE GENERATED",
        "value": "₹1.81 Cr"
      },
      {
        "label": "BOOKINGS GENERATED",
        "value": "1,721"
      }
    ],
    "gaugeScore": 92,
    "gaugeLabel": "Digital Performance Score",
    "scoreBars": [
      {
        "score": 95,
        "max": 100,
        "label": "User Experience (UX)"
      },
      {
        "score": 95,
        "max": 100,
        "label": "Campaign Health Metrics"
      }
    ],
    "statusCards": [
      {
        "label": "Rooms Capacity",
        "value": "6 Rooms"
      },
      {
        "label": "Direct Bookings Rate",
        "value": "43%"
      },
      {
        "label": "Consolidated Ad-Spend",
        "value": "37.50 Lakhs"
      }
    ],
    "pieData": [
      {
        "name": "Direct Bookings",
        "value": 43,
        "color": "#10b981"
      },
      {
        "name": "OTA Portals",
        "value": 47,
        "color": "#0ea5e9"
      },
      {
        "name": "Offline Groups",
        "value": 10,
        "color": "#f43f5e"
      }
    ],
    "bulletPoints": [
      "Ran high-impact Meta and Google Ads campaigns targeted at premium luxury travellers to scale direct bookings and brand inquiry conversions.",
      "Constructed commission-free direct booking integrations, synchronizing room rates and rate parity controls across booking networks.",
      "Handled premium social content curation and digital marketing, showcasing the property's 6 room inventory, guest suites, and amenities."
    ]
  },
  {
    "id": "the-johri-jaipur",
    "title": "THE JOHRI JAIPUR",
    "client": "THE JOHRI JAIPUR",
    "propertyType": "Homestay",
    "location": "Jaipur, Rajasthan",
    "capacity": "5 Rooms",
    "services": [
      "INSTAGRAM HANDLING",
      "GOOGLE ADS",
      "META ADS",
      "TECH SUPPORT",
      "OTA PROFILE"
    ],
    "tagline": "Deployed optimized direct booking channels for The Johri Jaipur in Jaipur, Rajasthan, converting 30% bookings commission-free and securing a 5.5x ROAS on digital media campaigns.",
    "imgSrc": "https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?auto=format&fit=crop&w=1200&q=80",
    "imgSrcMobile": "https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?auto=format&fit=crop&crop=faces,edges&w=800&h=1600&q=80",
    "kpis": [
      {
        "label": "REVENUE GENERATED",
        "value": "₹1.51 Cr"
      },
      {
        "label": "BOOKINGS GENERATED",
        "value": "1,434"
      }
    ],
    "gaugeScore": 94,
    "gaugeLabel": "Digital Performance Score",
    "scoreBars": [
      {
        "score": 90,
        "max": 100,
        "label": "User Experience (UX)"
      },
      {
        "score": 95,
        "max": 100,
        "label": "Campaign Health Metrics"
      }
    ],
    "statusCards": [
      {
        "label": "Rooms Capacity",
        "value": "5 Rooms"
      },
      {
        "label": "Direct Bookings Rate",
        "value": "30%"
      },
      {
        "label": "Consolidated Ad-Spend",
        "value": "18.00 Lakhs"
      }
    ],
    "pieData": [
      {
        "name": "Direct Bookings",
        "value": 30,
        "color": "#10b981"
      },
      {
        "name": "OTA Portals",
        "value": 65,
        "color": "#0ea5e9"
      },
      {
        "name": "Offline Groups",
        "value": 5,
        "color": "#f43f5e"
      }
    ],
    "bulletPoints": [
      "Ran high-impact Meta and Google Ads campaigns targeted at premium luxury travellers to scale direct bookings and brand inquiry conversions.",
      "Constructed commission-free direct booking integrations, synchronizing room rates and rate parity controls across booking networks.",
      "Handled premium social content curation and digital marketing, showcasing the property's 5 room inventory, guest suites, and amenities."
    ]
  },
  {
    "id": "the-belgadia-palace",
    "title": "THE BELGADIA PALACE",
    "client": "THE BELGADIA PALACE",
    "propertyType": "Homestay",
    "location": "Mayurbhanj, Odisha",
    "capacity": "11 Rooms",
    "services": [
      "INSTAGRAM HANDLING",
      "META ADS",
      "TECH SUPPORT",
      "OTA PROFILE"
    ],
    "tagline": "Deployed optimized direct booking channels for The Belgadia Palace in Mayurbhanj, Odisha, converting 42% bookings commission-free and securing a 5.0x ROAS on digital media campaigns.",
    "imgSrc": "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1200&q=80",
    "imgSrcMobile": "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&crop=faces,edges&w=800&h=1600&q=80",
    "kpis": [
      {
        "label": "REVENUE GENERATED",
        "value": "₹3.31 Cr"
      },
      {
        "label": "BOOKINGS GENERATED",
        "value": "3,155"
      }
    ],
    "gaugeScore": 96,
    "gaugeLabel": "Digital Performance Score",
    "scoreBars": [
      {
        "score": 92,
        "max": 100,
        "label": "User Experience (UX)"
      },
      {
        "score": 97,
        "max": 100,
        "label": "Campaign Health Metrics"
      }
    ],
    "statusCards": [
      {
        "label": "Rooms Capacity",
        "value": "11 Rooms"
      },
      {
        "label": "Direct Bookings Rate",
        "value": "42%"
      },
      {
        "label": "Consolidated Ad-Spend",
        "value": "15.00 Lakhs"
      }
    ],
    "pieData": [
      {
        "name": "Direct Bookings",
        "value": 42,
        "color": "#10b981"
      },
      {
        "name": "OTA Portals",
        "value": 52,
        "color": "#0ea5e9"
      },
      {
        "name": "Offline Groups",
        "value": 6,
        "color": "#f43f5e"
      }
    ],
    "bulletPoints": [
      "Ran high-impact Meta and Google Ads campaigns targeted at premium luxury travellers to scale direct bookings and brand inquiry conversions.",
      "Constructed commission-free direct booking integrations, synchronizing room rates and rate parity controls across booking networks.",
      "Handled premium social content curation and digital marketing, showcasing the property's 11 room inventory, guest suites, and amenities."
    ]
  },
  {
    "id": "mary-budden-estate",
    "title": "MARY BUDDEN ESTATE",
    "client": "MARY BUDDEN ESTATE",
    "propertyType": "Homestay",
    "location": "Binsar, Uttarakhand",
    "capacity": "8 Rooms",
    "services": [
      "INSTAGRAM HANDLING",
      "GOOGLE ADS",
      "META ADS",
      "TECH SUPPORT",
      "OTA PROFILE"
    ],
    "tagline": "Deployed optimized direct booking channels for Mary Budden Estate in Binsar, Uttarakhand, converting 28% bookings commission-free and securing a 4.5x ROAS on digital media campaigns.",
    "imgSrc": "https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=1200&q=80",
    "imgSrcMobile": "https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&crop=faces,edges&w=800&h=1600&q=80",
    "kpis": [
      {
        "label": "REVENUE GENERATED",
        "value": "₹2.41 Cr"
      },
      {
        "label": "BOOKINGS GENERATED",
        "value": "2,294"
      }
    ],
    "gaugeScore": 97,
    "gaugeLabel": "Digital Performance Score",
    "scoreBars": [
      {
        "score": 93,
        "max": 100,
        "label": "User Experience (UX)"
      },
      {
        "score": 98,
        "max": 100,
        "label": "Campaign Health Metrics"
      }
    ],
    "statusCards": [
      {
        "label": "Rooms Capacity",
        "value": "8 Rooms"
      },
      {
        "label": "Direct Bookings Rate",
        "value": "28%"
      },
      {
        "label": "Consolidated Ad-Spend",
        "value": "24.00 Lakhs"
      }
    ],
    "pieData": [
      {
        "name": "Direct Bookings",
        "value": 28,
        "color": "#10b981"
      },
      {
        "name": "OTA Portals",
        "value": 69,
        "color": "#0ea5e9"
      },
      {
        "name": "Offline Groups",
        "value": 3,
        "color": "#f43f5e"
      }
    ],
    "bulletPoints": [
      "Ran high-impact Meta and Google Ads campaigns targeted at premium luxury travellers to scale direct bookings and brand inquiry conversions.",
      "Constructed commission-free direct booking integrations, synchronizing room rates and rate parity controls across booking networks.",
      "Handled premium social content curation and digital marketing, showcasing the property's 8 room inventory, guest suites, and amenities."
    ]
  },
  {
    "id": "elite-exped",
    "title": "ELITE EXPED",
    "client": "ELITE EXPED",
    "propertyType": "Adventure Experience",
    "location": "Himalayas, Nepal",
    "capacity": "15 Rooms",
    "services": [
      "INSTAGRAM HANDLING",
      "META ADS"
    ],
    "tagline": "Deployed optimized direct booking channels for Elite Exped in Himalayas, Nepal, converting 38% bookings commission-free and securing a 5.5x ROAS on digital media campaigns.",
    "imgSrc": "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1200&q=80",
    "imgSrcMobile": "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&crop=faces,edges&w=800&h=1600&q=80",
    "kpis": [
      {
        "label": "REVENUE GENERATED",
        "value": "₹1.89 Cr"
      },
      {
        "label": "BOOKINGS GENERATED",
        "value": "2,250"
      }
    ],
    "gaugeScore": 91,
    "gaugeLabel": "Digital Performance Score",
    "scoreBars": [
      {
        "score": 96,
        "max": 100,
        "label": "User Experience (UX)"
      },
      {
        "score": 90,
        "max": 100,
        "label": "Campaign Health Metrics"
      }
    ],
    "statusCards": [
      {
        "label": "Rooms Capacity",
        "value": "15 Rooms"
      },
      {
        "label": "Direct Bookings Rate",
        "value": "38%"
      },
      {
        "label": "Consolidated Ad-Spend",
        "value": "1.80 Cr"
      }
    ],
    "pieData": [
      {
        "name": "Direct Bookings",
        "value": 38,
        "color": "#10b981"
      },
      {
        "name": "OTA Portals",
        "value": 58,
        "color": "#0ea5e9"
      },
      {
        "name": "Offline Groups",
        "value": 4,
        "color": "#f43f5e"
      }
    ],
    "bulletPoints": [
      "Ran high-impact Meta and Google Ads campaigns targeted at premium luxury travellers to scale direct bookings and brand inquiry conversions.",
      "Constructed commission-free direct booking integrations, synchronizing room rates and rate parity controls across booking networks.",
      "Handled premium social content curation and digital marketing, showcasing the property's 15 room inventory, guest suites, and amenities."
    ]
  },
  {
    "id": "skydive-dubai-vip",
    "title": "SKYDIVE DUBAI VIP",
    "client": "SKYDIVE DUBAI VIP",
    "propertyType": "Adventure Experience",
    "location": "Dubai, UAE",
    "capacity": "20 Rooms",
    "services": [
      "INSTAGRAM HANDLING",
      "GOOGLE ADS",
      "META ADS",
      "TECH SUPPORT",
      "OTA PROFILE"
    ],
    "tagline": "Deployed optimized direct booking channels for Skydive Dubai VIP in Dubai, UAE, converting 41% bookings commission-free and securing a 7.0x ROAS on digital media campaigns.",
    "imgSrc": "https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=1200&q=80",
    "imgSrcMobile": "https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&crop=faces,edges&w=800&h=1600&q=80",
    "kpis": [
      {
        "label": "REVENUE GENERATED",
        "value": "₹2.52 Cr"
      },
      {
        "label": "BOOKINGS GENERATED",
        "value": "3,000"
      }
    ],
    "gaugeScore": 92,
    "gaugeLabel": "Digital Performance Score",
    "scoreBars": [
      {
        "score": 97,
        "max": 100,
        "label": "User Experience (UX)"
      },
      {
        "score": 91,
        "max": 100,
        "label": "Campaign Health Metrics"
      }
    ],
    "statusCards": [
      {
        "label": "Rooms Capacity",
        "value": "20 Rooms"
      },
      {
        "label": "Direct Bookings Rate",
        "value": "41%"
      },
      {
        "label": "Consolidated Ad-Spend",
        "value": "2.25 Cr"
      }
    ],
    "pieData": [
      {
        "name": "Direct Bookings",
        "value": 41,
        "color": "#10b981"
      },
      {
        "name": "OTA Portals",
        "value": 52,
        "color": "#0ea5e9"
      },
      {
        "name": "Offline Groups",
        "value": 7,
        "color": "#f43f5e"
      }
    ],
    "bulletPoints": [
      "Ran high-impact Meta and Google Ads campaigns targeted at premium luxury travellers to scale direct bookings and brand inquiry conversions.",
      "Constructed commission-free direct booking integrations, synchronizing room rates and rate parity controls across booking networks.",
      "Handled premium social content curation and digital marketing, showcasing the property's 20 room inventory, guest suites, and amenities."
    ]
  },
  {
    "id": "ahilya-fort",
    "title": "AHILYA FORT",
    "client": "AHILYA FORT",
    "propertyType": "Homestay",
    "location": "Maheshwar, Madhya Pradesh",
    "capacity": "15 Rooms",
    "services": [
      "GOOGLE ADS",
      "META ADS",
      "OTA PROFILE"
    ],
    "tagline": "Deployed optimized direct booking channels for Ahilya Fort in Maheshwar, Madhya Pradesh, converting 45% bookings commission-free and securing a 5.2x ROAS on digital media campaigns.",
    "imgSrc": "https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?auto=format&fit=crop&w=1200&q=80",
    "imgSrcMobile": "https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?auto=format&fit=crop&crop=faces,edges&w=800&h=1600&q=80",
    "kpis": [
      {
        "label": "REVENUE GENERATED",
        "value": "₹4.52 Cr"
      },
      {
        "label": "BOOKINGS GENERATED",
        "value": "4,302"
      }
    ],
    "gaugeScore": 98,
    "gaugeLabel": "Digital Performance Score",
    "scoreBars": [
      {
        "score": 94,
        "max": 100,
        "label": "User Experience (UX)"
      },
      {
        "score": 88,
        "max": 100,
        "label": "Campaign Health Metrics"
      }
    ],
    "statusCards": [
      {
        "label": "Rooms Capacity",
        "value": "15 Rooms"
      },
      {
        "label": "Direct Bookings Rate",
        "value": "45%"
      },
      {
        "label": "Consolidated Ad-Spend",
        "value": "21.00 Lakhs"
      }
    ],
    "pieData": [
      {
        "name": "Direct Bookings",
        "value": 45,
        "color": "#10b981"
      },
      {
        "name": "OTA Portals",
        "value": 50,
        "color": "#0ea5e9"
      },
      {
        "name": "Offline Groups",
        "value": 5,
        "color": "#f43f5e"
      }
    ],
    "bulletPoints": [
      "Ran high-impact Meta and Google Ads campaigns targeted at premium luxury travellers to scale direct bookings and brand inquiry conversions.",
      "Constructed commission-free direct booking integrations, synchronizing room rates and rate parity controls across booking networks.",
      "Handled premium social content curation and digital marketing, showcasing the property's 15 room inventory, guest suites, and amenities."
    ]
  }
];
